name: loveloveraid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  window_size: ^0.1.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  just_audio: ^0.10.0
  record: ^6.0.0
  google_speech: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/service_account.json
    - .env
    - .env.local